### ISSUE TITLE
TODOs for journal submission

### ISSUE THREAD

**Issue by hjsuh94** [pangtao22/planning_through_contact#62]
**Writing** 

Reviewer 2 
- [ ] Clarify equivalence of randomized and analytic smoothing 
- [ ] Clarify interior point methods warm starting 
- [ ] Clarify timestep vs. Anitescu's relaxation 
- [ ] Clarify smoothing coming from Anitescu vs. smoothing 
- [ ] Forward mode Autodiff vs. Analytic gradients
- [x] Get rid of statements about B.  

Reviewer 6
- [ ] Full dynamics gradients are obtained by chaining dJi/dq and dphi_i/dq, which has collision-geometry discontinuities. 
- [ ] Does this scheme differ from relaxing the complementary slackness constraint? 
- [ ] Table of hyperparameters 
- [ ] Explain more on contact sampling
- [ ] Code release 

Reviewer 7
- [ ] Section 1, summary of how each sections are connected. 
- [ ] Table 1, show expressions?
- [ ] Our dynamics are not convex, we just approximate it that way.
- [ ] Physical intuition for quasi-dynamic and convexification. 
- [ ] Where does smoothed contact mechanics fit in algorithms 2,3,4?
- [ ] Discuss limitations
- [ ] Include a few more references 

Reviewer 8
- [ ] Comparison with RL?
- [ ] Validate on real robot 

**Experiments**

Reviewer 2
- [ ] Verify validity of quasidynamic assumption on sim2drake
  - [ ] Planar Hand 
  - [ ] Planar Pushing 
  - [ ] Allegro Hand
  - [ ] Iiwa-Bimanual setup
  - [ ] Allegro Pen
  - [ ] Allegro Book
  - [ ] Allegro Door 
- [ ] Verify validity of quasidynamic assumption on open-loop hardware execution on Bimanual Iiwa

**Comment by pangtao-BDAI** [comment]
Resbumitted!
